service: railroad-faas
provider:
  name: aws
  runtime: nodejs10.x

plugins:
  - serverless-offline

functions:
  ping:
    handler: handler.bCZ9eOrbB.ping
    events:
      - http:
         path: health/ping
         method: get

